In [1]:
import pandas as pd

In [2]:
paths = {
    'online_retail': '../data/online_retail.csv',
    'profiling_table': '../outputs/profiling_table.csv'
}

In [3]:
# import dataset
df = pd.read_csv(paths['online_retail'])

In [4]:
# inspect dataset
df.head(3)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/10 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/10 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/10 8:26,2.75,17850.0,United Kingdom

## Part A Column profiling table

In [8]:
# create profile table
summary = pd.DataFrame({
    "col_name": df.columns,
    "dtype": df.dtypes,
    "n_missing": [df[col].isna().sum() for col in df.columns],
    "missing_rate": [round(df[col].isna().mean()*100, 2) for col in df.columns],
    "is_unique": df.columns.duplicated(),
    "n_unique": [df[col].nunique() for col in df.columns],
    "sample_values": [list(df[col].unique()[0:3]) for col in df.columns]
})
summary.to_csv(paths['profiling_table'], index=False)
summary

,col_name,dtype,n_missing,missing_rate,is_unique,n_unique,sample_values
InvoiceNo,InvoiceNo,str,0,0.00,False,25900,"[536365, 536366, 536367]"
StockCode,StockCode,str,0,0.00,False,4070,"[85123A, 71053, 84406B]"
Description,Description,str,1454,0.27,False,4223,"[WHITE HANGING HEART T-LIGHT HOLDER, WHITE MET..."
Quantity,Quantity,int64,0,0.00,False,722,"[6, 8, 2]"
InvoiceDate,InvoiceDate,str,0,0.00,False,23260,"[12/1/10 8:26, 12/1/10 8:28, 12/1/10 8:34]"
UnitPrice,UnitPrice,float64,0,0.00,False,1630,"[2.55, 3.39, 2.75]"
CustomerID,CustomerID,float64,135080,24.93,False,4372,"[17850.0, 13047.0, 12583.0]"
Country,Country,str,0,0.00,False,38,"[United Kingdom, France, Australia]"

In [6]:
df.describe() # stats summary of numerical columns

            Quantity      UnitPrice     CustomerID
count  541909.000000  541909.000000  406829.000000
mean        9.552250       4.611114   15287.690570
std       218.081158      96.759853    1713.600303
min    -80995.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13953.000000
50%         3.000000       2.080000   15152.000000
75%        10.000000       4.130000   16791.000000
max     80995.000000   38970.000000   18287.000000

## Part B Short Questions

#### 1. rows/cols numbers

In [7]:
print(f'{df.shape[0]} is the number of rows')
print(f'{df.shape[1]} is the number of columns')

541909 is the number of rows
8 is the number of columns

#### 2. top 3 columns by missing rate

In [8]:
missing_rates = {}
for col in df.columns:
    missing_rate = df[col].isna().mean()
    missing_rates[col] = missing_rate
top3missing = sorted(missing_rates.items(), key = lambda x: x[1], reverse = True)[:3]
top3missing
print(top3missing)

[('CustomerID', np.float64(0.249266943342886)), ('Description', np.float64(0.002683107311375157)), ('InvoiceNo', np.float64(0.0))]

#### 3. top 5 countries by count

In [9]:
top5countries = df.groupby('Country').count().index[:5]
print(top5countries)

Index(['Australia', 'Austria', 'Bahrain', 'Belgium', 'Brazil'], dtype='str', name='Country')

#### 4. number of unique InvoiceNo

In [10]:
print(f'{df['InvoiceNo'].nunique()} is the number of unique InvoiceNo')

25900 is the number of unique InvoiceNo

#### 5. missing rate of CustomerID

In [11]:
print(f'{round(df['CustomerID'].isna().mean() * 100 , 2)}% is the missing rate of CustomerID')

24.93% is the missing rate of CustomerID

#### 6. number of rows with Quantity <= 0, and with UnitPrice <= 0

In [12]:
print(f'{sum(df['Quantity']<= 0)} is number of rows with Quantity <= 0')
print(f'{sum(df['UnitPrice']<= 0)} is number of rows with Quantity <= 0')

10624 is number of rows with Quantity <= 0
2517 is number of rows with Quantity <= 0

## Part C Index Awareness Experiment

#### 1. the type/shape of `df.index`

In [13]:
df.index

RangeIndex(start=0, stop=541909, step=1)

#### 2. what changes after `reset_index()`
Reset the index of the DataFrame, returns a new DataFrame with a default integer index and the old index as a column

In [14]:
df.reset_index()

,index,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/10 8:26,2.55,17850.0,United Kingdom
1,1,536365,71053,WHITE METAL LANTERN,6,12/1/10 8:26,3.39,17850.0,United Kingdom
2,2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/10 8:26,2.75,17850.0,United Kingdom
3,3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/10 8:26,3.39,17850.0,United Kingdom
4,4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/10 8:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...,...
541904,541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/11 12:50,0.85,12680.0,France
541905,541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/11 12:50,2.10,12680.0,France
541906,541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/11 12:50,4.15,12680.0,France
541907,541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/11 12:50,4.15,12680.0,France
541908,541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/11 12:50,4.95,12680.0,France

#### 3. difference between `iloc` and `loc` selection

In [15]:
df_index = df.set_index('InvoiceNo', drop=False)
df_index.iloc[:5] # Integer position: select first 8 rows defined by index InvoiceNo

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
InvoiceNo,,,,,,,,
536365,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/10 8:26,2.55,17850.0,United Kingdom
536365,536365,71053,WHITE METAL LANTERN,6,12/1/10 8:26,3.39,17850.0,United Kingdom
536365,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/10 8:26,2.75,17850.0,United Kingdom
536365,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/10 8:26,3.39,17850.0,United Kingdom
536365,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/10 8:26,3.39,17850.0,United Kingdom

In [16]:
# df_index.loc[:5]    ### TypeError because InvoiceNo 0-5 does not exist
df.loc[:5] # Label based: can only work if index is exactly the number given by the slicer

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/10 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/10 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/10 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/10 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/10 8:26,3.39,17850.0,United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,12/1/10 8:26,7.65,17850.0,United Kingdom